version: '3.3'

services:
  resource-db:
    image: postgres:17-alpine
    container_name: resource-db
    environment:
      POSTGRES_DB: resource-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
  song-db:
    image: postgres:17-alpine
    container_name: song-db
    environment:
      POSTGRES_DB: song-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55433:5432"
