spring:
  application:
    name: ResourceService

  http:
    codecs:
      max-in-memory-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/resources
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/resources
    username: admin
    password: admin123
