spring:
  application:
    name: ResourceService
  http:
    codecs:
      max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://localhost:55432/resource-db
    username: postgres
    password: postgres
service:
  song:
    url: http://localhost:8081

