spring:
  application:
    name: ResourceService
  http:
    codecs:
      max-in-memory-size: 10MB
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:55432/resource-db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
service:
  song:
    url: ${SERVICE_GATEWAY_URL:http://localhost:8081}
server:
  port: 8080

eureka:
  instance:
    # Frequency of heartbeats sent by the client to the server
    lease-renewal-interval-in-seconds: 5
  client:
    # Frequency of registry data retrieval from the server to the client's local cache
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

